apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'com.richardsolomou.ras_code.composereditor'
version = '0.0.0'

android {
  namespace 'expo.modules.ras_code.composereditor'
  compileSdk rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
